services:
  - type: web
    name: clothes-changer-by-lab
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: CDREAM_MODEL
        sync: false
      - key: CDREAM_VERSION
        sync: false
      - key: NEXT_PUBLIC_MAX_FILE_MB
        value: 15
